
## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
## ANCHORS
## ======================================================================
pxf_dev_server_image_check: &pxf_dev_server_image
  - task: check_docker_images_and_tag
    timeout: 45m
    image: ccp-7
    params:
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
      GOOGLE_PROJECT_ID: {{google-project-id}}
      GOOGLE_ZONE: {{google-zone}}
      IMAGE_LIST: "gpdb5-centos6-test-pxf-hdp2 gpdb5-centos7-test-pxf-cdh gpdb5-centos7-test-pxf-hdp2 gpdb5-centos7-test-pxf-hdp3 gpdb6-centos6-test-pxf-hdp2 gpdb6-centos7-test-pxf-cdh gpdb6-centos7-test-pxf-hdp2 gpdb6-centos7-test-pxf-hdp3 gpdb6-ubuntu18.04-test-pxf-hdp2"
    config:
      platform: linux
      inputs:
        - name: pxf_src
      run:
        path: pxf_src/concourse/scripts/check_docker_images_and_tag.bash

pxf_dev_mapr_image_check: &pxf_dev_mapr_image
  - task: check_docker_images_and_tag
    timeout: 30m
    image: ccp-7
    params:
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
      GOOGLE_PROJECT_ID: {{google-project-id}}
      GOOGLE_ZONE: {{google-zone}}
      IMAGE_LIST: "gpdb5-centos7-test-pxf-mapr gpdb6-centos7-test-pxf-mapr"
    config:
      platform: linux
      inputs:
        - name: pxf_src
      run:
        path: pxf_src/concourse/scripts/check_docker_images_and_tag.bash

## ======================================================================
## RESOURCES
## ======================================================================
resources:
  - name: ccp-7
    type: docker-image
    icon: docker
    source:
      repository: pivotaldata/ccp
      tag: 7

  - name: pxf-dev-base-cloudbuild-trigger
    type: git
    icon: git
    source:
      branch: {{pxf-git-branch}}
      uri: https://github.com/greenplum-db/pxf.git
      paths:
        - concourse/docker/pxf-dev-base

  - name: dockerfile-gpdb-pxf-dev-server
    type: git
    icon: git
    source:
      branch: {{pxf-git-branch}}
      uri: https://github.com/greenplum-db/pxf.git
      paths:
        - concourse/docker/pxf-dev-server

  - name: dockerfile-gpdb-pxf-mapr
    type: git
    icon: git
    source:
      branch: {{pxf-git-branch}}
      uri: https://github.com/greenplum-db/pxf.git
      paths:
        - concourse/docker/mapr

  - name: base-images-trigger
    type: git
    icon: git
    source:
      uri: {{gp-image-baking-repo-uri}}
      branch: {{gp-image-baking-repo-branch}}
      private_key: {{gp-image-baking-repo-key}}
      paths:
        - images/docker/gpdb6/gpdb6-centos6-test
        - images/docker/gpdb6/gpdb6-centos7-test
        - images/docker/gpdb6/gpdb6-ubuntu18.04-test

  - name: pxf-build-dependencies-trigger
    type: gcs
    icon: google-drive
    source:
      bucket: data-gpdb-ud-pxf-build-resources
      json_key: {{data-gpdb-ud-google-json-key}}
      versioned_file: build-dependencies/pxf_commit_sha

## ======================================================================
## JOBS
## ======================================================================
jobs:
  - name: Check upstream base images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
      - get: base-images-trigger
        trigger: true
      - get: pxf-build-dependencies-trigger
        trigger: true
    - task: trigger_builds
      image: ccp-7
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        TRIGGER_LIST: "pxf-dev-base"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/trigger_cloudbuild.bash

  - name: Check pxf-dev-base images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
        trigger: true
      - get: base-images-trigger
        passed: [Check upstream base images]
        trigger: true
      - get: pxf-build-dependencies-trigger
        passed: [Check upstream base images]
        trigger: true
    - task: check_docker_images_and_tag
      timeout: 30m
      image: ccp-7
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        IMAGE_LIST: "gpdb5-centos6-test-pxf gpdb5-centos7-test-pxf gpdb6-centos6-test-pxf gpdb6-centos7-test-pxf gpdb6-ubuntu18.04-test-pxf"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/check_docker_images_and_tag.bash
    - task: trigger_builds
      image: ccp-7
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        TRIGGER_LIST: "pxf-dev-server pxf-dev-mapr"
      config:
        platform: linux
        inputs:
          - name: pxf_src
        run:
          path: pxf_src/concourse/scripts/trigger_cloudbuild.bash

  - name: Check pxf-dev-server images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: dockerfile-gpdb-pxf-dev-server
        trigger: true
    - do: *pxf_dev_server_image

  - name: Check pxf-dev-server images 2
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
      - get: pxf-build-dependencies-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
      - get: base-images-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
    - do: *pxf_dev_server_image

  - name: Check pxf-dev-mapr images
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: dockerfile-gpdb-pxf-mapr
        trigger: true
    - do: *pxf_dev_mapr_image

  - name: Check pxf-dev-mapr images 2
    max_in_flight: 1
    plan:
    - in_parallel:
      - get: ccp-7
      - get: pxf_src
        resource: pxf-dev-base-cloudbuild-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
      - get: pxf-build-dependencies-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
      - get: base-images-trigger
        passed: [Check pxf-dev-base images]
        trigger: true
    - do: *pxf_dev_mapr_image
