-- @description query01 for PXF Profiles feature checking Profile not exists error.

-- start_matchsubs
--                                                                                               
-- # create a match/subs
--
-- m/\/gpdb\/v\d+\//
-- s/v\d+/SOME_VERSION/
--
-- m/file:.*;/
-- s/file:.*; lineNumber: \d+; columnNumber: \d+;/SOME_ERROR_LOCATION/g
--
-- m/PXF server error.*(ProfileConfException).*/
-- s/PXF server error.*/PXF server error : Failed to instantiate [org.greenplum.pxf.service.profile.ProfilesConf]: Constructor threw exception; nested exception is org.greenplum.pxf.service.profile.ProfileConfException: Profiles configuration path could not be loaded/
--
-- m/DETAIL/
-- s/DETAIL/CONTEXT/
--
-- m/pxf:\/\/(.*)\/pxf_automation_data/
-- s/pxf:\/\/.*\/pxf_automation_data\/[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}/pxf:\/\/pxf_automation_data/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- end_matchsubs
SELECT * FROM pxf_profiles_small_data ORDER BY name;
