-- start_ignore
-- end_ignore
-- @description query01 for PXF test for cloud access where server is specified, no credentials are specified, and configuration file contains invalid credentials
--
-- start_matchsubs
--
-- # create a match/subs
--
-- m/PXF server error.*(com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden).*/
-- s/PXF server error.*/PXF server error : com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden/
--
-- m/Make sure no configuration files under.*/
-- s|Make sure no configuration files under.*|Make sure no configuration files under 'server-dir' specify the property 'defaultFS' with the value starting with 'hdfs://', which is incompatible with profile filesystem 's3a'. Check the PXF logs located in the 'logs-dir' directory on host 'mdw' or 'set client_min_messages=LOG' for additional details.|
--
-- m/DETAIL/
-- s/DETAIL/CONTEXT/
--
-- m/pxf:\/\/(.*)\/pxf_automation_data/
-- s/pxf:\/\/.*PROFILE/pxf:\/\/pxf_automation_data?PROFILE/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- end_matchsubs

SELECT *  FROM cloudaccess_server_no_credentials_invalid_config;
